name: ESLint, Prettier, and TypeScript

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  eslint-prettier-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: ESLint check
        run: npm run lint
        env:
          CI: true
      - name: Prettier write
        run: npm run prettier:write
      - name: Prettier check
        run: npm run prettier:check
      - name: TypeScript check
        run: npm run type-check -- --composite false
        env:
          CI: true
